### ISSUE TITLE
plugitGetUser raise an error in the Simple Django Client standalone mode

### ISSUE THREAD

**Issue by rspt** [ebu/PlugIt#25]
In branch [update2015](https://github.com/ebu/PlugIt/tree/update2015), the following line raise an error when included in a template:

```
{% plugitGetUser c.author as tmpuser %}{{ tmpuser.first_name }} {{ tmpuser.last_name }}
```

**Comment by barroco** [comment]
Thanks for reporting this, could you please provide a stack trace?

**Comment by rspt** [comment]
```
Internal Server Error: /plugIt/templates/
Traceback (most recent call last):
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rspt/Dev/ebu/PlugIt/Simple Django client/plugIt/views.py", line 760, in main
    (result, menu) = render_data(context, templateContent, proxyMode, rendered_data, plugItMenuAction)
  File "/Users/rspt/Dev/ebu/PlugIt/Simple Django client/plugIt/views.py", line 472, in render_data
    result = template.render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 201, in render
    nodelist.append(node.render(context))
  File "/Users/rspt/Dev/ebu/EBUio/venv/lib/python2.7/site-packages/django/template/base.py", line 1168, in render
    context[self.target_var] = func(*resolved_args, **resolved_kwargs)
  File "/Users/rspt/Dev/ebu/PlugIt/Simple Django client/plugIt/templatetags/plugit_tags.py", line 54, in plugitGetUser
    user = generate_user(pk=str(pk))
  File "/Users/rspt/Dev/ebu/PlugIt/Simple Django client/plugIt/views.py", line 105, in generate_user
    user.ebuio_orga_member = user.ebuio_member
AttributeError: 'NoneType' object has no attribute 'ebuio_member'
[27/Nov/2015 11:23:46] "GET /plugIt/templates/ HTTP/1.1" 500 171842
```

Do you need something else?
